<?php
/**
 * lemocms
 * ============================================================================
 * 版权所有 2018-2027 lemocms，并保留所有权利。
 * 网站地址: https://www.lemocms.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/9/4
 */
namespace app\admin\controller;
use think\facade\Request;
use think\facade\View;
class Addons extends Base{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /*
     * 插件列表
     */
    public function index(){

        if(Request::isPost()) {
            $list = Db::name('addons')->select();
            return $result = ['code'=>0,'msg'=>'获取成功!','data'=>$list];
        }
        return View::fetch();

    }
    /**
     * 插件安装卸载
     */
    public function install(){
        $condition['type'] = input('post.type');
        $condition['code'] = input('post.code');
        $update['status'] = input('post.install');
        $model = Db::name('addons');
        //卸载插件时 删除配置信息
        if($update['status']==0){
            $row = Db::name('addons')->where($condition)->delete();
        }else{
            $row = $model->where($condition)->update($update);
        }
        if($row){
            $info['code'] = 1;
            $info['url'] = url($condition['type']);
            $info['msg'] = $update['status'] ? '安装成功!' : '卸载成功!';
        }else{
            $info['code'] = 0;
            $info['msg'] = $update['status'] ? '安装失败' : '卸载失败';
        }
        return $info;
    }
}