<?php
/**
 * lemocms
 * ============================================================================
 * 版权所有 2018-2027 lemocms，并保留所有权利。
 * 网站地址: https://www.lemocms.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/9/4
 */
namespace app\admin\controller;
use app\common\model\WxFans;
use app\common\model\WxMaterial;
use app\common\model\WxMaterialInfo;
use app\common\model\WxMsgHistory;
use app\common\model\WxReply;
use app\common\model\WxTag;
use EasyWeChat\Kernel\Messages\News;
use EasyWeChat\Kernel\Messages\NewsItem;
use think\facade\Db;
use think\facade\Request;
use think\facade\View;
use app\common\model\WxAccount;
use util\WechatApp;
use EasyWeChat\Kernel\Messages\Text;
use EasyWeChat\Kernel\Messages\Article;
use EasyWeChat\Kernel\Messages\Image;
use EasyWeChat\Kernel\Messages\Video;
use EasyWeChat\Kernel\Messages\Voice;

class Wechat extends Base{
    //图片（image）: 2M，支持bmp/png/jpeg/jpg/gif格式
    //
    //语音（voice）：2M，播放长度不超过60s，mp3/wma/wav/amr格式
    //
    //视频（video）：10MB，支持MP4格式
    //
    //缩略图（thumb）：64KB，支持JPG格式
    protected $imageValidate = [
        'image' => 'filesize:2048|fileExt:jpg,png,gif,jpeg'

    ];
    protected $videoValidate = [
        'file' => 'filesize:10240|fileExt:avi,rmvb,3gp,flv,mp4,rm'

    ];
    protected $voiceValidate = [
        'file' => 'filesize:2048|fileExt:mp3,wma,wav,amr'

    ];
    protected $thumbValidate = [
        'image' => 'filesize:64|fileExt:jpg'

    ];
    protected $where =[];
    public $wechatApp;
    public $store_id;
    protected $wechatAccount ;
    protected $materialType = ['news','video','voice','image','music'];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated
        $wechatApp  = new WechatApp();
        $this->wechatApp = $wechatApp->wechatApp;
        $this->store_id = $wechatApp->store_id;
        $this->wechatAccount = WxAccount::where('status',1)->where('store_id',$this->store_id)->find();
        if($this->wechatAccount){
            $this->where= ['store_id'=>$this->store_id,'wx_aid'=>$this->wechatAccount->id];

        }else{
            $this->wechatAccount = WxAccount::where('store_id',$this->store_id)->find();
        }
    }



    /**
     ************************公众号管理****************************
     */
    public function index(){
        if (Request::isPost()) {
            $list = Db::name('wx_account')->alias('a')
                ->leftJoin('wx_type t','t.type_id=a.type')
                ->field('a.*,t.name as type_name')
                ->select()->toArray();

            return $result = ['code' => 0, 'msg' => '获取成功!', 'data' => $list,];
        }
        return View::fetch();

    }

    public function add(){
        if (Request::isPost()) {
            $data = Request::post();
            try{
                $this->validate($data, 'WxAccount');
            }catch (\Exception $e){
                $this->error($e->getMessage());
            }


            $res = WxAccount::create($data);
            if ($res) {
                $this->success('添加成功',url('index'));
            } else {
                $this->success('添加失败');
            }
        }

        $view = [
            'info' => '',
            'title' => '添加',
        ];
        View::assign($view);
        return View::fetch();
    }

    public function edit(){
        if (Request::isPost()) {
            $data = Request::post();
            try {
                $this->validate($data, 'WxAccount');
            } catch (\Exception $e) {
                $this->error($e->getMessage());
            }
            $res = WxAccount::update($data);
            if ($res) {
                $this->success('修改成功', url('index'));
            } else {
                $this->success('修改失败');
            }
        }
        $info = WxAccount::find(Request::get('id'));
        $view = [
            'info' => $info,
            'title' => '修改',
        ];
        View::assign($view);
        return View::fetch('add');

    }
    public function state(){

        $id = Request::post('id');
        if($id){
            $info = WxAccount::find($id);
            $info->status = $info->status==1?0:1;
            if($info->status==1){

                $list = WxAccount::where('status',1)->where('id','<>',$info->id)->select();
                if($list){
                    foreach ($list as $k=>$v){

                        $v->status=0;

                        $v->save();
                    }
                }
            }
            $info->save();
            $this->success('修改成功');

        }else{
            $this->error('非法数据');
        }
    }
    public function delete(){
        $id = Request::post('id');
        if($id){
            WxAccount::destroy($id);
            $this->success('删除成功');

        }else{
            $this->error('非法数据');
        }

    }


    /**
     ************************菜单管理****************************
     */


    public function menu(){
        $baseURL = Request::domain();
        $view = [
            'baseURL'=>$baseURL,
        ];
        View::assign($view);
        return View::fetch();

    }
    public function getWxAccount(){

        $info =  WxAccount::order('status desc')->select();

        return $info;

    }

    public function changeApp(){
        $appid = Request::post('app_id');
        $isAPP = WxAccount::where('app_id',$appid)->value('status');
        $button['button']=[];
        if(!$isAPP){
            $this->error('失败','',$button);
        }
        //获取当前菜单
        $menu = $this->wechatApp->menu->list();
        if(isset($menu['menu'])){

            $button = $menu['menu'];
            $this->success('成功','',$button);
        }else{
            $this->error('失败','',$button);
        }

    }



    // 添加微信菜单
    public function addWeixinMenu(){
        $data = Request::post();
        $app_id = $data['app_id'];
        $isApp = WxAccount::where('store_id',$this->store_id)->where('app_id',$app_id)->value('status');
        if($isApp !=1){
            $this->error('公众号没有对接成功');
        }
        $menu = $data['menu'];
        if (!empty($menu)) {
            $res = $this->wechatApp->menu->create($menu['button']);
            if($res['errcode']==0){
                $this->success('添加成功');
                //WxMenu::create($menu['button']);
            }else{

                $this->error('创建失败');
            }


        }
        $this->error('创建失败');
    }

    public function updataWechatMenu()
    {
        $menu =  $this->wechatApp->menu->list();
        $this->success('更新成功');

    }
    public function menuDel(){

        $res = $this->wechatApp->menu->delete(); // 全部
        if($res['errcode']==0){
            $this->success('删除成功');
        }else{
            $this->error('删除失败');
        }
    }

    /**
     ************************粉丝管理***************************
     */
    public function fans(){

        if (Request::isPost()) {
            $wx_aid = Request::post('wx_aid');
            if(!$wx_aid){
                $wx_aid =  $this->wechatAccount->id;
            }
            if(!$wx_aid){
                return $result = ['code' => 0,'msg' => '获取失败!请对接公众号',];

            }
            $keys = Request::post('keys','','trim');
            $page = Request::post('page') ? Request::post('page') : 1;
            $list=Db::name('wx_fans')
                ->where('nickname','like','%'.$keys.'%')
                ->where('wx_aid',$wx_aid)
                ->order('fans_id desc')
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();
            $tag = WxTag::where('store_id',$this->store_id)->where('wx_aid',$wx_aid)
                ->select()->toArray();

            foreach ($list['data'] as $k=>$v){
                $list['data'][$k]['tag_list'] = $tag;
            }
            return $result = ['code' => 0, 'msg' => '获取成功!', 'data' => $list['data'],'count'=>$list['total'],'tag'=>$tag];
        }
        $wxAccount = WxAccount:: where('store_id',$this->store_id)
            ->select();
        $view = [
                'title'=>'粉丝',
                'info'=>'',
                'wxAccount'=>$wxAccount,
            ];
        View::assign($view);
        return View::fetch();
    }


    public function fansAysn(){
        $wx_aid = Request::post('wx_aid');
        if(!$wx_aid){
            $this->error('请求错误');
        }
        $wxAccount = $this->wechatAccount;
        if(!$wxAccount){
            $this->error('公众号还未对接成功，请先对接');
        }
        $usersOpenidList = $this->wechatApp->user->list();
        $users = [];
        if($usersOpenidList['total']>0){
            foreach ($usersOpenidList['data']['openid'] as $k=>$v){
                $users[$k] =  $this->wechatApp->user->get($v);
            }
        }
        $WxFansModel = new WxFans();

        Db::startTrans();
        try {
            foreach ($users as $k=>$v){
                $v['wx_aid'] = $wx_aid;
                $v['tagid_list'] = json_encode($v['tagid_list']);

                $fans = $WxFansModel::where($this->where)
                    ->where('openid',$v['openid'])
                    ->find();
                if($fans){
                    $res = $WxFansModel::where($this->where)
                        ->where('openid',$v['openid'])
                        ->where('fans_id',$fans['fans_id'])
                        ->update($v);
                    if($res){
                        Db::rollback();
                    }
                }else{
                    $v['store_id'] = $this->store_id;
                    $v['update_time'] = time();
                    $v['nickname_encode'] = json_encode($v['nickname']);
                    $WxFansModel::create($v);
                }
            }
            // 提交事务
            Db::commit();
            $this->success('同步成功');
        } catch (\Exception $e) {
             //回滚事务
            Db::rollback();
            $this->error('同步失败');
        }

        $this->success('同步成功');

    }
    //粉丝标签
    public function fansTagGroup(){
        if(Request::isPost()){
            $id = Request::post('id');
            $tag = Request::post('tag');
            $wxFans = WxFans::where('fans_id',$id)->find();
            $tags = WxTag::where('store_id',$this->store_id)
                ->where('wx_aid',$wxFans->wx_aid)->find();
            $wxFans->tag = $tag;
            $res = $this->wechatApp->user_tag->tagUsers([$wxFans->openid],$tags['tag_id']);
            if($res){

                $wxFans->save();
                $this->success('更新成功');
            }else{
                $this->error('更新失败');

            }
        }

    }
    //粉丝标签管理
    public function tag(){
        if (Request::isPost()) {
            $wx_aid = Request::post('wx_aid');
            if(!$wx_aid){
                $wx_aid =  $this->wechatAccount->id;
            }
            if(!$wx_aid){
                return $result = ['code' => 0,'msg' => '获取失败!请对接公众号',];

            }
            $keys = Request::post('keys','','trim');
            $page = Request::post('page') ? Request::post('page') : 1;
            $list=Db::name('wx_tag')
                ->where('name','like','%'.$keys.'%')
                ->where('wx_aid',$wx_aid)
                ->order('id desc')
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();

            return $result = ['code' => 0, 'msg' => '获取成功!', 'data' => $list['data'],'count'=>$list['total']];
        }


        $wxaccount = WxAccount::where('store_id',$this->store_id)->select();

        $view = ['title'=>'标签', 'info'=>'', 'wxaccount'=>$wxaccount];
        View::assign($view);
        return View::fetch();

    }
    public function tagState(){

        if (Request::isPost()) {
            $id = Request::post('id');
            if (empty($id)) {
                $this->error('ID不存在!');
            }
            $adv = WxTag::find($id);
            $status = $adv['status'] == 1 ? 0 : 1;
            $adv->status = $status;
            $adv->save();
            $this->success('修改成功!');
        }

    }
    public function tagAysn()
    {
        if(Request::isPost()){
            $wx_aid = $this->wechatAccount->id;
            $tags = $this->wechatApp->user_tag->list();

            foreach($tags['tags'] as $k=>$v){
                $info = WxTag::where('name',$v['name'])->find();
                $v['tag_id'] = $v['id'];

                if(!$info){
                    $v['store_id'] = $this->store_id;
                    $v['wx_aid'] = Request::post('wx_aid')?Request::post('wx_aid'):$wx_aid;
                    unset($v['id']);
                    WxTag::create($v);
                }else{
                    $v['id'] = $info['id'];
                    WxTag::update($v);

                }

            }
            $this->success('同步成功');

        }

        $this->error('非法操作');

    }
    public function tagAdd()
    {

        if(Request::isPost()){
            $data  = Request::post();
            if($data){
                $data['store_id'] = $this->store_id;
                $this->validate($data,'WxTag');

                $res = $this->wechatApp->user_tag->create($data['name']);
                $data['tag_id'] = $res['tag']['id'];
                if($res){
                    WxTag::create($data);
                    $this->success('添加成功');
                }else{
                    $this->error('添加失败');
                }

            }else{
                $this->error('添加失败');
            }


        }
        $wx_aid = Request::get('wx_aid');
        $view = [
            'title'=>'添加',
            'info'=>['wx_aid'=>$wx_aid],
        ];

        View::assign($view);
        return View::fetch('tag_add');
    }

    public function tagEdit()
    {
        if(Request::isPost()){
            $data  = Request::post();
            if($data){
                $data['store_id'] = $this->store_id;
                $tag = WxTag::find($data['id']);

                $res = $this->wechatApp->user_tag->update($tag['tag_id'],$data['name']);
                if($res['errcode']==0){
                    WxTag::update($data);
                    $this->success('修改成功');
                }else{
                    $this->error('修改失败');
                }

            }else{
                $this->error('修改失败');
            }


        }
        $id = Request::get('id');
        $info  = WxTag::find($id);

        $view = [
            'title'=>'修改',
            'info'=>$info,
            'wx_aid'=>$info['wx_aid'],
        ];

        View::assign($view);
        return View::fetch('tag_add');

//        $this->wechatApp->user_tag->update($tagId, $name);
    }

    public function tagDel()
    {
        $id = Request::post('id');
        $info = WxTag::find($id);
        $res = $this->wechatApp->user_tag->delete($info['tag_id']);
        if($res['errcode']==0){
            WxTag::destroy($id);
        }else{
            $this->error('删除失败');
        }
        $this->success('删除成功!');

    }

    /**
     ************************历史消息管理***************************
     */

    public function message()
    {
        if(Request::isPost()){
            $keys = Request::post('keys','','trim');
            $page = Request::post('page') ? Request::post('page') : 1;
            $list=Db::name('wx_msg_history')
                ->where('store_id',$this->store_id)
                ->where('wx_aid',$this->wechatAccount->id)
                ->where('nickname','like','%'.$keys.'%')
                ->order('id desc')
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();

            return $result = ['code'=>0,'msg'=>'获取成功!','data'=>$list['data'],'count'=>$list['total']];
        }

        return View::fetch();
    }

    public function messageDel()
    {
        if(Request::isPost()){
            $id = Request::post('id');
            WxMsgHistory::destroy($id);
            $this->success('成功');
        }

    }
    public function messageReply()
    {
        if(Request::isPost()){
            $material_id = Request::post('material_id');
            $openid = Request::post('openid');
            $msg_type = Request::post('msg_type');
            $material = WxMaterial::find($material_id);
            if($material){
                $media_id = $material->media_id;

            }else{
                $media_id = '';
            }
            $message = WxReply::where($this->where)->where('type','default')->value('data');

            switch ($msg_type) {
                case 'text':
                    $data = Request::post('data');
                    $message = new Text($data);
                    break;

                case 'image':
                    if(WxMaterial::where('media_id',$media_id)->find()){

                        $message =  new Image($media_id);
                    }
                    break;

                case 'news':
                    $new = WxMaterialInfo::where($this->where)->where('material_id', $material_id)->find();
                    if ($new) {
                        $newsList[] = new NewsItem([
                            'title' => $new->title,
                            'description' => $new->digest,
                            'url' => $new->url,
                            'image' => $new->cover,
                        ]);
                        $message = new News($newsList);
                    }else{
                        $message = WxReply::where($this->where)->where('type','default')->value('data');

                    }
                    break;
                case 'video':
                    if(WxMaterial::where('media_id',$media_id)->find()) {

                        $message =  new Video($media_id, $material->file_name, $material->des);
                    }

                    break;
                case 'voice':
                    if(WxMaterial::where('media_id',$media_id)->find()) {

                        $message =  new Voice($media_id);
                    }
                    break;
                default:

                    break;
            }

            $result = $this->wechatApp->customer_service->message($message)->to($openid)->send();

            if ($result['errcode'] == 0) {
                $this->success('发送成功');
            } else {
                $this->error('发送失败');

            }
        }else{
            $wx_aid  = Request::get('wx_aid');
            $id  = Request::get('id');
            $info = WxMsgHistory::where('store_id',$this->store_id)->find($id);
            $user = $this->wechatApp->user->get($info->openid);
            $materialGroup = $this->getMaterialGroup();

            $view = ['title'=>'回复','user'=>$user,'info'=>$info,'materialGroup'=>$materialGroup];
            View::assign($view);
            return View::fetch();
        }

    }

    /**
     ************************素材管理***************************
     */
    public function material(){

        if (Request::isPost()) {
            $wx_aid = Request::post('wx_aid');
            if(!$wx_aid){
                $wx_aid = WxAccount::where('status',1)
                    ->where('store_id',$this->store_id)
                    ->value('id');
            }
            if(!$wx_aid){
                return $result = ['code' => 0,'msg' => '获取失败!请对接公众号',];

            }
            $keys = Request::post('keys','','trim');
            $page = Request::post('page') ? Request::post('page') : 1;
            $list=Db::name('wx_material')
                ->where('nickname','like','%'.$keys.'%')
                ->where('wx_aid',$wx_aid)
                ->order('fans_id desc')
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();
            return $result = ['code' => 0, 'msg' => '获取成功!', 'data' => $list['data'],'count'=>$list['total']];
        }
        $materialGroup = $this->getMaterialGroup();
        $view = [
            'title'=>'素材',
            'info'=>'',
            'materialGroup'=>$materialGroup,
        ];
        View::assign($view);
        return View::fetch();


    }
    //添加图文素材
    public function materialAdd(){

        if(Request::isPost()){

            $data = Request::post('content');

            try{

                foreach ($data as $k => $v) {
                    $info = explode('`-`',$v);
                    $article= new Article($data[$k]);
                    $articles[$k] = $article;

                }
                $res = $this->wechatApp->material->uploadArticle($articles);

            }catch (\Exception $e){

                $this->error($e->getMessage());
            }

            $WxMaterialData = [
                'store_id'=>$this->store_id,
                'wx_aid'=>$this->wechatAccount->id,
                'type'=>'news',
                'media_id'=>$res['media_id'],
                ];

            $material =    $this->getMaterialByMediaId($res['media_id']);

            // 启动事务
            Db::startTrans();
            try {
                $mat= WxMaterial::create($WxMaterialData);
                if(isset($data[0])){
                    //多图文
                    foreach ($data as $k=>$v) {

                        $data[$k]['cover'] = WxMaterial::where('media_id', $data[$k]['thumb_media_id'])->value('media_url');
                        $data[$k]['local_cover'] = WxMaterial::where('media_id', $data[$k]['thumb_media_id'])->value('local_cover');
                        $data[$k]['store_id'] = $this->store_id;
                        $data[$k]['wx_aid'] = $this->wechatAccount->id;
                        $data[$k]['url'] = $material['news_item'][$k]['url'];
                        $data[$k]['material_id'] = $mat->id;
                    }

                    $matinfo=  Db::name('WxMaterialInfo')->insertAll($data);

                    }else{

//                    单图文
                    $data['cover'] = WxMaterial::where('media_id', $data['thumb_media_id'] )->value('media_url');
                    $data['local_cover'] = WxMaterial::where('media_id', $data['thumb_media_id'])->value('local_cover');
                    $data['store_id'] =$this->store_id;
                    $data['wx_aid'] = $this->wechatAccount->id;
                    $data['url'] = $material['news_item'][0]['url'];
                    $data['material_id'] = $mat->id;
                        $matinfo=  Db::name('WxMaterialInfo')->insert($data);

                    }
                // 提交事务
                Db::commit();
                $this->success('成功');

            } catch (\Exception $e) {
                // 回滚事务
                Db::rollback();
                $this->error($e->getMessage());

            }


        }
        $params['name'] = 'container';
        $params['content'] = '';
        $view = [
            'info' => [],
            'title' => '添加',
            'ueditor'=>build_ueditor($params),
        ];
        View::assign($view);
        return View::fetch();
    }

    public function materialEdit(){
        if(Request::isPost()){
            $data = Request::post('content');
            $id = Request::post('mediaId');
            $mediaId = WxMaterial::where('id', $id)->value('media_id');
            try {


                foreach ($data as $k => $v) {

                    $article = new Article($data[$k]);

                    $res = $this->wechatApp->material->updateArticle($mediaId, $article, $k);

                }

            } catch (\Exception $e) {

                $this->error($e->getMessage());
            }


            $material =  $this->getMaterialByMediaId($mediaId);

            // 启动事务
            Db::startTrans();
            try {
                if(isset($data[0])){
                    //多图文
                    foreach ($data as $k=>$v) {
                        $data[$k]['id'] =
                        $data[$k]['cover'] = WxMaterial::where('media_id', $data[$k]['thumb_media_id'])->value('media_url');
                        $data[$k]['store_id'] = $this->store_id;
                        $data[$k]['wx_aid'] = $this->wechatAccount->id;
                        $data[$k]['url'] = $material['news_item'][$k]['url'];
                        $data[$k]['material_id'] =$id;
                        $data[$k]['update_time'] = time();
                    }
                    $WxMaterialInfoModel = new WxMaterialInfo();
                    $matinfo=  $WxMaterialInfoModel->saveAll($data);

                }else{

//                    单图文
                    $data['cover'] = WxMaterial::where('media_id', $data['thumb_media_id'] )->value('media_url');
                    $data['store_id'] =$this->store_id;
                    $data['wx_aid'] = $this->wechatAccount->id;
                    $data['url'] = $material['news_item'][0]['url'];
                    $data['material_id'] = $id;
                    $data['update_time'] = time();
                    $matinfo=  Db::name('WxMaterialInfo')->save($data);

                }
                // 提交事务
                Db::commit();
                $this->success('成功');

            } catch (\Exception $e) {
                // 回滚事务
                Db::rollback();
                $this->error($e->getMessage());

            }


        }
        $id = Request::get('id');
        $info = WxMaterialInfo::where('material_id',$id)->select()->toArray();
        $params['name'] = 'container';
        $params['content'] = '';
        $view = [
            'title'=>'修改',
            'info'=>$info,
            'ueditor'=>build_ueditor($params),
        ];
        View::assign($view);

        return View::fetch('material_add');
    }

    public function materialDel(){

        $id = Request::post('id');
        $material = WxMaterial::find($id);
        //删除微信媒体库
        $this->wechatApp->material->delete($material->media_id);

        if($material['type']=='news'){
            $info = WxMaterialInfo::where($this->where)->where('material_id',$id)->delete();
            if($info && $material->delete()){
                $this->success('删除成功');
            }else{
                $this->error('删除失败');

            }
        }else{
            if($material->delete()){

                $this->success('删除成功');
            }else{
                $this->error('删除失败');

            }
        }

    }
    // 发送消息
    public function materialSend(){
        if (Request::isPost()) {
            $id = Request::post('id');
            $info = WxMaterial::find($id);
            $res = $this->sendAll($info);
            $this->showError($res);
            $this->success('发送成功');
        } else {
            $this->error('发送失败');

        }

    }
    //预览消息

    public function materialPreview(){
        if(Request::isPost()){
            $wxname = Request::post('wxname');
            $id = Request::post('id');
            $info = WxMaterial::find($id);
            $res = $this->preview($info,$wxname);

            $this->showError($res);
            $this->success('发送成功');

        }else{
            $this->error('发送失败');

        }


    }

    protected function preview($info,$wxname){

        // 发送预览群发消息给指定的 openId 用户
        //$this->wechatApp->broadcasting->previewText($text, $openId);
        //$this->wechatApp->broadcasting->previewNews($mediaId, $openId);
        //$this->wechatApp->broadcasting->previewVoice($mediaId, $openId);
        //$this->wechatApp->broadcasting->previewImage($mediaId, $openId);
        //$this->wechatApp->broadcasting->previewVideo($message, $openId);
        //$this->wechatApp->broadcasting->previewCard($cardId, $openId);
        //发送预览群发消息给指定的微信号用户
        //$wxanme 是用户的微信号，比如：notovertrue
        //
        //$this->wechatApp->broadcasting->previewTextByName($text, $wxname);
        //$this->wechatApp->broadcasting->previewNewsByName($mediaId, $wxname);
        //$this->wechatApp->broadcasting->previewVoiceByName($mediaId, $wxname);
        //$this->wechatApp->broadcasting->previewImageByName($mediaId, $wxname);
        //$this->wechatApp->broadcasting->previewVideoByName($message, $wxname);
        //$this->wechatApp->broadcasting->previewCardByName($cardId, $wxname);

        $type = $info->type;
        switch ($type){
            case 'text':
                $res = $this->wechatApp->broadcasting->previewTextByName($info->media_id,$wxname);
                break;

            case 'image':

                $res = $this->wechatApp->broadcasting->previewImageByName($info->media_id, $wxname);

                break;

            case 'news':
                $res = $this->wechatApp->broadcasting->previewNewsByName($info->media_id, $wxname);

                break;
            case 'video':
                $res = $this->wechatApp->broadcasting->previewVideoByName($info->media_id, $wxname);


                break;
            case 'voice':
                $res = $this->wechatApp->broadcasting->previewVoiceByName($info->media_id, $wxname);
                break;
            case 'card':
                $res = $this->wechatApp->broadcasting->previewCardByName($info->media_id, $wxname);
                break;
            default:
                $res = $this->wechatApp->broadcasting->previewTextByName($info->media_id,$wxname);

                break;
        }

        return $res;

    }

    protected function sendAll($info){


        $type = $info->type;
        switch ($type){

            case 'image':

                $res = $this->wechatApp->broadcasting->sendImage($info->media_id);

                break;

            case 'news':
                $res = $this->wechatApp->broadcasting->sendNews($info->media_id);

                break;
            case 'video':
                $res = $this->wechatApp->broadcasting->sendVideo($info->media_id);


                break;
            case 'voice':
                $res = $this->wechatApp->broadcasting->sendVoice($info->media_id);
                break;
            case 'card':
                $res = $this->wechatApp->broadcasting->sendCard($info->media_id);
                break;
            default:
                $res = $this->wechatApp->broadcasting->image($info->media_id);

                break;
        }

        return $res;



    }
    /**
     ************************回复设置***************************
     */
    public function reply(){

        $type = Request::get('type','default');
        $typeList = [
            [
                'url' => url('reply',['type'=>'default']),
                'item' => "默认回复",
                "type" => 'default'
            ],
            [    'url' => url('reply',['type'=>'subscribe']),
                'item' => "关注回复",
                "type" => 'subscribe'
            ],

            [ 'url' => url('reply',['type'=>'keyword']),
                'item' => "关键字回复",
                "type" =>'keyword'
            ],

           ];


        if ($type == 'default') {

            $info = Db::name('wx_reply')
                ->where($this->where)
                ->where('type', $type)
                ->select();
        } elseif ($type == 'subscribe') {
            $info = Db::name('wx_reply')
                ->where($this->where)
                ->where('type' ,$type)
                ->select
                ();

        } elseif($type == 'keyword') {
            $info = Db::name('wx_reply') ->where($this->where)
                ->where('type' ,$type)
                ->select();
        }
        $view = [
            'title'=>'粉丝',
            'type'=>$type,
            'info' =>$info,
            'typeList'=>$typeList,
            ];
        View::assign($view);
        return View::fetch();


    }

    public function replyAdd(){

        if(Request::isPost()){
            $data = Request::post();
            $data['store_id'] = $this->store_id;
            $data['wx_aid'] = $this->wechatAccount->id;
            if(!$data['type']){
                $data['type']='keyword';
            }
            $res = WxReply::create($data);
            if ($res) {
                $this->success('添加成功',url('index'));
            } else {
                $this->success('添加失败');
            }
        }

        $view = [
            'info' => [],
            'title' => '添加',
            'materialGroup' => $this->getMaterialGroup(),

        ];
        View::assign($view);


        return View::fetch();


    }

    public function replyEdit(){
        if (Request::isPost()) {
            $data = Request::post();
            $data['store_id'] = $this->store_id;
            $data['wx_aid'] = $this->wechatAccount->id;
            $res = WxReply::update($data);
            if ($res) {
                $this->success('修改成功',url('index'));
            } else {
                $this->success('修改失败');
            }
        }
        $info = WxReply::find(Request::get('id'));
        $view = [
            'info' => $info,
            'title' => '修改',
            'materialGroup' => $this->getMaterialGroup(),
        ];
        View::assign($view);
        return View::fetch('reply_add');

    }
    public function replayDel(){

        $id = Request::post('id');
        WxReply::destroy($id);
        $this->success('删除成功');

    }

    /**
     ************************二维码管理***************************
     */


    /**
     ************************接口返回***************************
     */

    //获取素材
    public function getMaterialByType(){
        $type = Request::post('type');
//      $type text 素材的类型，图片（image）、视频（video）、语音 （voice）、图文（news）

//      $res = $this->wechatApp->material->list($type,0,100);
        $res =  WxMaterial::where($this->where)->where('type',$type)
            ->where($this->where)->select()->toArray();
        if($type=='news'){
            foreach ($res as $k=>$v){
                $res[$k]['groupList'] = WxMaterialInfo::where($this->where)->where('material_id',$v['id'])->select()->toArray();
            }
        }
        $this->success('成功','',$res);


    }

    /**
     * @param $type
     * @param int $id
     * @return array|\think\Collection|\think\Model|null
     * 获取素材
     */
    protected function getMaterialGroup(){
        $materialGroup = [];
        foreach ($this->materialType as $k=>$v){
            if($v=='news'){

                $weixin_material_info = Db::name('wx_material')->where('type','news')->select()->toArray();
                if (!empty($weixin_material_info)) {
                    foreach($weixin_material_info as $key=>$value){

                        $item_info = Db::name('wx_material_info')->where('material_id' , $value['id'])->select()->toArray();
                        $weixin_material_info[$key]['item_info'] = $item_info;
                    }
                }
                $materialGroup[$v] = $weixin_material_info;

            }else{

                $weixin_material_info = Db::name('wx_material')->where('type',$v)->select()->toArray();

                $materialGroup[$v] = $weixin_material_info;

            }
        }
        return $materialGroup;

    }

    /**
     ********************************上传素材接口***************************************
     */

    protected function uploads($type){

        //获取上传文件表单字段名
        $fileKey = array_keys(request()->file());
        for ($i = 0; $i < count($fileKey); $i++) {
            //获取表单上传文件
            $file = request()->file($fileKey[$i]);
            try {
                validate($type)
                    ->check(object_array($file));
                $savename = \think\facade\Filesystem::disk('public')->putFile('uploads', $file);

                $path[] = '/storage/' . $savename;
            } catch (\think\exception\ValidateException $e) {
                $path = '';
                $error = $e->getMessage();
            }
        }
        if (!empty($path)) {
            $result['code'] = 1;
            //分辨是否截图上传，截图上传只能上传一个，非截图上传可以上传多个
            if (Request::param('responseType') == 'json') {
                $result["url"] = $path[0];
            } else {
                $result["url"] = $path[0];
            }
            $result['msg'] = '上传成功';
            return $result;
        } else {
            //上传失败获取错误信息
            $result['url'] = '';
            $result['msg'] = $error;
            $result['code'] = 0;
            return $result;
        }


    }
    public function imageUpload(){

        $res = $this->uploads($this->imageValidate);
        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadImage('./'.$res['url']);
            $this->showError($result);
            $data  = [
                'store_id'=> $this->store_id,
                'wx_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $result['url'],
                'local_cover'=> $res['url'],
                'type'=> 'image',
            ];

            $r = WxMaterial::create($data);
            if($r){
                $this->success('上传成功','',$result);
            }else{
                $this->error('上传失败');

            }
        }else{
            $this->error('上传失败');

        }
    }

    public function videoUpload(){
        $data = Request::post();
        if(!$data['url'] || !$data['file_name'] || !$data['des']){
            $this->error('数据不能为空');
        }
        $result = $this->wechatApp->material->uploadVideo('.'.$data['url'],$data['file_name'],$data['des']);
        $this->showError($result);
        $resource = $this->wechatApp->material->get($result['media_id']);
        $datas  = [
            'store_id'=> $this->store_id,
            'wx_aid'=> $this->wechatAccount->id,
            'media_id'=> $result['media_id'],
            'media_url'=> $resource['down_url'],
            'type'=> 'video',
            'file_name'=> $data['file_name'],
            'des'=> $data['des'],
        ];
        $result['url'] = $resource['down_url'];

        $r = WxMaterial::create($datas);
        if($r){
            $this->success('上传成功','',$result);
        }else{
            $this->error('上传失败');

        }


    }

    public function voiceUpload(){
        $res = $this->uploads($this->voiceValidate);
        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadVoice('./'.$res['url']);
            $this->showError($result);
            $resource = $this->wechatApp->material->get($result['media_id']);

            $data  = [
                'store_id'=> $this->store_id,
                'wx_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $resource['down_url'],
                'type'=> 'image',
            ];
            $result['url'] = $resource['down_url'];
            $r = WxMaterial::create($data);
            if($r){
                $this->success('上传成功','',$result);
            }else{
                $this->error('上传失败');

            }
        }else{
            $this->error('上传失败');

        }

    }


    public function thumbUpload(){
        $res = $this->uploads($this->thumbValidate);
        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadThumb('./'.$res['url']);
            $this->showError($result);
            $data  = [
                'store_id'=> $this->store_id,
                'wx_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $result['url'],
                'type'=> 'image',
            ];

            $r = WxMaterial::create($data);
            if($r){
                $this->success('上传成功',$result['url']);
            }else{
                $this->error('上传失败');

            }
        }else{
            $this->error('上传失败');

        }


    }

    public function UeditUploadImage(){

        $res = $this->uploads($this->imageValidate);
        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadImage('./'.$res['url']);
            $this->showError($result);
            $data  = [
                'store_id'=> $this->store_id,
                'wx_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $result['url'],
                'local_cover'=> $res['url'],
                'type'=> 'image',
            ];

            $r = WxMaterial::create($data);
            $data = ['state'=>'SUCCESS','url'=>$data['media_url']];

        }else{
            $data = ['state'=>'SUCCESS','url'=>''];

        }
        return json_encode($data);

    }

    public function UeditUploadVideo(){
        $res = $this->uploads($this->videoValidate);

        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadVideo('./'.$res['url'],$res['url'],$res['url']);
            $this->showError($result);
            $resource = $this->wechatApp->material->get($result['media_id']);

            $data  = [
                'store_id'=> $this->store_id,
                'wx_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $resource['down_url'],
                'type'=> 'video',
                'file_name'=> $res['url'],
                'des'=> $res['url'],
            ];
            $result['url'] = $resource['down_url'];
            $r = WxMaterial::create($data);

            $data = ['state'=>'SUCCESS','url'=>$resource['down_url']];
        }else{
            $data = ['state'=>'SUCCESS','url'=>''];

        }
        return json_encode($data);

    }

    public function UeditUploaVoice(){

        $res = $this->uploads($this->voiceValidate);

        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadVoice('./'.$res['url']);
            $this->showError($result);
            $resource = $this->wechatApp->material->get($result['media_id']);

            $data  = [
                'store_id'=> $this->store_id,
                'wx_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $resource['down_url'],
                'type'=> 'image',
            ];
            $result['url'] = $resource['down_url'];
            $r = WxMaterial::create($data);

            $data = ['state'=>'SUCCESS','url'=>$resource['down_url']];
        }else{
            $data = ['state'=>'SUCCESS','url'=>''];

        }
        return json_encode($data);


    }
    public function getListImage(){
            $list = WxMaterial::where($this->where)->where('type','image')->select();
            $data = ['state'=>'SUCCESS','start'=>0,'total'=>count($list),'list'=>[]];
            if($list){
                foreach ($list as $k=>$v) {
                    $data['list'][$k]['url'] = $v['media_url'];
                    $data['list'][$k]['mtime'] = time();
                }
            }

            return json_encode($data);

    }
    // 微信返回数据
    protected  function showError($res){
        if(isset($res['errcode']) && $res['errcode']>0){
            $this->error($res['errmsg']);
        }

    }

    //获取媒体素材
    protected function getMaterialByMediaId($mediaId){
        $resource = $this->wechatApp->material->get($mediaId);
        $this->showError($resource);
        return $resource;

    }
}